server:
    port: 8082
    servlet:
        context-path: /flights
spring:
    datasource:
        password: root@1234
        url: jdbc:mysql://localhost:3306/hr
        username: root
    jpa:
        show-sql: true
